export interface Game {
  game_id?: number; // This will be generated by the database
  player_x_name: string;
  player_o_name: string;
  current_turn: "X" | "O";
  game_status: "in_progress" | "complete" | "draw";
}

export interface Move {
  move_id?: number; // This will be generated by the database
  game_id: number;
  player_type: "X" | "O";
  position: number; // Assuming 0-8 for positions on the board
  move_time: Date;
}
